// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huluwnszqqtmldjiosle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bHV3bnN6cXF0bWxkamlvc2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTY2MjcsImV4cCI6MjA3Mzc3MjYyN30.da4JHHtr7caXqo5jkFD--X3Q3AC28-G0YJG3VqlkqRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});